import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '@/theme';
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <html>
        <body>
          <Box
            component="main"
            sx={{ backgroundColor: 'background.default', p: 0 }}
          >
            {children}
          </Box>
        </body>
      </html>
    </ThemeProvider>
  );
}
