'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import ShopHeader from '@/components/ShopHeader/ShopHeader';
import PrimarySearchAppBar from '@/components/Test/TestHeader';
import Container from '@mui/material/Container';
import Footer from '@/components/Footer/Footer';
import Basket from '@/components/Basket/Basket';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [basketIsOpen, setBasketIsOpen] = React.useState<boolean>(false);

  return (
    <html lang="en">
      <body style={{ backgroundColor: '#F6F9FC' }}>
        <PrimarySearchAppBar basketOpenHandler={() => setBasketIsOpen(true)} />
        {/*<ShopHeader />*/}
        <main>
          {children}
          {/*<Container maxWidth="xl">{children}</Container>*/}
        </main>
        {/*<Footer />*/}
        <Basket
          isOpen={basketIsOpen}
          closeHandler={() => setBasketIsOpen(false)}
        />
      </body>
    </html>
  );
}
